title: Building a Command Line Environment for .NET Development with Rake
permalink: building-a-command-line-environment-for-net-development-with-rake
tinylink: 25
published_at: 2010-07-15
location: Calgary
